usr/share/snmp/mib2c*.conf etc/snmp
usr/bin/mib2c
usr/bin/mib2c-update
usr/include/*
usr/lib/*/lib*.a
usr/lib/*/lib*.so
usr/lib/*/pkgconfig/netsnmp-agent.pc
usr/lib/*/pkgconfig/netsnmp.pc
# Install the "broke" headers
agent/mibgroup/struct.h	usr/include/net-snmp/agent
agent/mibgroup/util_funcs.h usr/include/net-snmp
agent/mibgroup/mibincl.h usr/include/net-snmp/library
agent/mibgroup/header_complex.h usr/include/net-snmp/agent
usr/bin/net-snmp-config
usr/share/man/man1/net-snmp-config.1
