.\" (C) Copyright 2019 Craig Small <csmall@debian.org>
.\"
.\" Redistribution and use in source and binary forms, with or without
.\" modification, are permitted provided that the following conditions
.\" are met:
.\" 1. Redistributions of source code must retain the above copyright
.\"    notice, this list of conditions and the following disclaimer.
.\" 2. Redistributions in binary form must reproduce the above copyright
.\"    notice, this list of conditions and the following disclaimer in the
.\"    documentation and/or other materials provided with the distribution.
.\" 3. Neither the name of the University nor the names of its contributors
.\"    may be used to endorse or promote products derived from this software
.\"    without specific prior written permission.
.\" .
.\" THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
.\" ``AS IS'' AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
.\" LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR
.\" A PARTICULAR PURPOSE ARE DISCLAIMED.  IN NO EVENT SHALL THE HOLDERS OR
.\" CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL,
.\" EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO,
.\" PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR
.\" PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF
.\" LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING
.\" NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
.\" SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
.\"
.TH SNMPPING 1 2019-08-29 "Net-SNMP"
.SH NAME
snmpping \- command an agent to ping a remote host
.SH SYNOPSIS
.B snmpget
[\fICOMMON OPTIONS\fR] \fIAGENT\fR \fIDESTINATION\fR
.SH DESCRIPTION
.B snmping
is an SNMP application that uses the DISMAN-PING-MIB to perform remote
pings from the specified \fIAGENT\fR to the remote \fIDESTINATION\fR.

The local host will send SNMPSET commands to the \fIAGENT\fR which, if
accepted will then ping the \fIDESTINATION\fR.

.B snmpping
will then poll the \fIAGENT\fR to obtain the ping results.

.SH "OPTIONS"
.TP
.BI \-Cc pings
The \fIAGENT\fR will send \fIpings\fR pings to the \fIDESTINATION\fR.
.TP
.BI \-Cs size
The \fIAGENT\fR will send pings that are \fIsize\fR bytes.
.PP
In addition to these options,
.B snmpping
takes the common options described in the
.I snmpcmd(1)
manual page.  
Note that 
.B snmpping

.SH "EXAMPLES"
The command:
.PP
    snmpping \-c private zeus hera
.PP
will get host \fBzeus\fR to ping host \fBhera\fR. Host \fBzeus\fR
would need to have \fBprivate\fR as a read-write community.
.SH SEE ALSO
.BR snmpcmd (1), variables (5).
